name = "test_remoteio_led"
description = "Remote I/O Protocol LED Test"
version = "1.0.0"

authors = ["Philip Munts"]
maintainers = ["Philip Munts <phil@munts.net>"]
maintainers-logins = ["pmunts"]

executables = ["test_remoteio_led"]
[[depends-on]]
remoteio = "^2.0.0"
