name = "test_simpleio_led"
description = "Linux Simple I/O Library LED Test"
version = "1.0.0"

authors = ["Philip Munts"]
maintainers = ["Philip Munts <phil@munts.net>"]
maintainers-logins = ["pmunts"]

executables = ["test_simpleio_led"]
[[depends-on]]
libsimpleio = "^2.0.0"
